
from time import sleep
#begin


while True:
    print("Het is een zaterdag ochtend je word wakker door een hard geluid en denkt woow wat is er aan de hand?")
    print("je loopt naar het raam en kijkt naar buiten en ziet kogels vliegen en un tank 3 blocken vederop")
    print("Je staat even stil na te denken wat je nu gaat doen?")
    sleep(2)
    print("Blijf ik om te helpen of vlucht ik?")
    print("A = Blijf")
    #print("B = Vlucht")

    keusen1 = input ()
    if keusen1 == "A":
        print("Okey wat gaan we nu doen...")
        sleep(1)
        print("We gaan eerst naar buiten en dan kijken we wat we uberhoud kunnen doen")
        sleep(1)
        print("Okey ik denk dat het handig is als we eerst wat straaten veder lopen...")
        sleep(3)
        print("Owh god er liggen hier dode mensen...")
        sleep(1)
        print("mischien had ik toch maar moeten vluchten....")
        sleep(2)
        print("WOOW WAT IS DAT?!")
        sleep(1)
        print("er vloog zonet een raket over me heen in un gebouw...")
        sleep(1)
        print("Okey ik moet echt wat gaan doen ik kan hier niet blijven staan...")
        sleep(2)
        print("Wat gaan we doen pakken we un geweer van een dood persoon of gaan we kijken of er nog wat te redden valt bij het gebouw?")
        print("A = Pak un geweer")
        print("B = Ga naar het gebouw")
        keusen2 = input ()
        if keusen2 == "A":
            print("Okey dat was heel vies maar we hebben un geweer er zit nog un magezine in met un paar kogels gok ik..")
            sleep(2)
            print("Volgens mij zie ik daar slechte mensen die op andere schieten ik moet nu gaan helpen")
            sleep(1)
            print("Je rent er naar toe en begint te schieten")
            sleep(1)
            print("Piew Piew Piew")
            print("Piew")
            sleep(3)
            print("okey dat was geen goed idee ik heb nog nooit un geweer vast gepakt en hier lig ik dan op de grond met 3 kogels in me borst...")
            sleep(3)
            print("_____________")
            print("The idiot ending..")
            sleep(80)
            break
        if keusen2 == "B":
            print("Je rent naar het gebouw en hoord geschreeuw je twijvelt geen seconden en rent naar binnen")
            sleep(1)
            print("Je bent nu al 2 trappen omhoog gerent en voelt dat het lastiger word om te ademen ")
            sleep(1)
            print("Je hoord het geluid van een klein kind huilen en een moeder schreeuwen om hulp...")
            sleep(2)
            print("Je hebt ze gevonden en bekijkt de situatie en het ziet er niet goed uit de moeder schreeuwt 'Zorg dat me kind eerst in veiligheid is!!' wat gaan we doen?")
            print("A = Probeer de moeder en kind tegelijketijd te redden")
            print("B = Probeer het kind te redden")
            Brand = input ()
            if Brand == "A":
                print("je geeft het kind je shirt om voor ze mond te doen en gooit hem op je rug de moeder pak je stevig vast bij der arm en ze doet haar voor haar mond")
                sleep(1)
                print("het kind is redelijk zwaar maar op dit punt kan je het niks scheelen de lucht word lastiger om adem te halen je loopt met de trap naar beneden")
                sleep(3)
                print("Je bent bijna buien totdat er un balk voor de uitgang valt")
                sleep(1)
                print("Je haalt het kind van je rug af en slaat un raam door je gooit half het kind het raam uit en helpt de moeder daarna...")
                sleep(1)
                print("je bent de laatste die uit het gebouw is begint te hoesten van alle rook die in je longen is gekomen je bedenkt heb ik nou de goeie keuzen gemaakt??")
                sleep(4)
                print("je krijgt bijna geen adem meer en begint licht in je hoofd te worden voordat je het weet lig je op de grond geen bewust meer van wat er allemaal gebreurt...")
                sleep(5)
                print("je gaat dood door al het vuil in je longen..")
                print("_____________")
                print("de held einden...")
                sleep(80)
                break
            if Brand == "B":
                print("Het kind is het er niet mee eens en schreeuwt ze moeders naam terwijl je je shirt tegen ze mond houd zodat hij minder stoffen in ze lichaam komen je rent naar de uitgang")
                sleep(4)
                print("Je bent net naar buiten terwijl je je omdraait om terug naar binnen tegaan valt er een balk voor de ingang en je bekijkt goed de situatie er is geen manier hoe je de moeder nog kan redden je staat al te hoesen in pijn van de lucht die je binnen hebt gekregen")
                sleep(5)
                print("Ondanks het niet je kind is kan je het niet over je hard laten om hem hier alleen achter te laten dus je neemt hem mee en gaat opzoek naar een veilige plek")
                sleep(4)
                print("omdat je een klein kind mee hebt bied iemand aan om mee te gaan achterin een auto naar un buurland hier 3 uur vandaan je accepteert het aanbod en komt na 3 uur aan bij je buurland")
                sleep(6)
                print("Je krijgt daar un verblijf het is niet veel maar is iets na 2 jaar is de oorlog voorbij en kunnen jullie weer terug naar huis..")
                sleep(5)
                print("__________")
                print("Ik weet niet wat ik hier van moet vinden Einden")